feat: Add C make/cmake application pipelines
epam/edp-tekton pull request #261
Opened 2024-08-09 09:47 UTC by Rolika4

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

## Checklist:
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Pull Request contain one commit. I squash my commits.

## Screenshots (if appropriate):

## Additional context
Add any other context or screenshots about the feature request here.

2024-08-12 14:01 UTC, SergK requested changes

2024-08-12 14:01 UTC, SergK commented on charts/pipelines-library/templates/tasks/edp-c.yaml
> +      description: The path where package.json of the project is defined.
are we ok with this description?

2024-08-12 14:01 UTC, SergK commented on charts/pipelines-library/templates/tasks/edp-c.yaml
> +      default: "golang:1.22-bookworm"
are we ok with this image?

2024-08-13 06:57 UTC, Rolika4 commented on charts/pipelines-library/templates/tasks/edp-c.yaml
> +      description: The path where package.json of the project is defined.
Update description

2024-08-13 06:57 UTC, Rolika4 commented on charts/pipelines-library/templates/tasks/edp-c.yaml
> +      default: "golang:1.22-bookworm"
Update image

2024-08-13 08:07 UTC, SergK approved these changes

2024-08-13 08:07 UTC, merged